function []=assayBrightFieldCytoTestNN()
%Usage This assay has been optimized for tracking cells imaged using bright-field microscopy using a 
%   nearest-neighbor algorithm. The assay tracks the cells, detects mitotic events and 
%records  tracking  data,  cell shape parameters and ancestry information to spreadsheets. 
%For each  tracked image,  an overlayed  image is saved to disk 
%that displays the  detected cell outlines,  cell IDs and  cell generation.

global functions_list;
functions_list=[];
%script variables
ImageFolder='C:/kam/H929_No_Position(8)';
ImageFilesRoot='Experiment-0002_Position(8)_t';
ImageExtension='.jpg';
StartFrame=1;
FrameCount=10;
TimeFrame=15;
FrameStep=1;
NumberFormat='%03d';
MaxFramesMissing=0;
OutputFolder=[ImageFolder '/output'];
AncestryFolder=[OutputFolder '/ancestry'];
AncestrySpreadsheet=[AncestryFolder 'ancestry.csv'];
ShapesSpreadsheet=[AncestryFolder 'shapes.csv'];
TracksFolder=[OutputFolder '/track'];
SegmentationFilesRoot=[TracksFolder '/grayscale'];
ImageFileBase=[ImageFolder '/' ImageFilesRoot];
GradientThreshold=1500;
ObjectArea=200;
ObjectReduce=1;
ClusterDist=21.5;
ClearBorder=true;
ClearBorderDist=2;
ResizeImageScale=0.5;
ResizeLabelMatrixScale=2;
ApproximationDistance=2.5;
MaxSearchRadius=200;
MinSearchRadius=50;
MinSecondDistance=5;
MaxDistRatio=0.6;
MaxAngleDiff=0.35;
NrParamsForSureMatch=5;
SearchRadiusPct=3;
MaxMergeDistance=23;
MaxSplitArea=400;
MaxSplitDistance=45;
MinSplitEccentricity=0.5;
MaxSplitEccentricity=0.95;
MinTimeForSplit=900;
MinLifespan=30;
FrontParams=[2 3];
DefaultParamWeights=[3 2 0 0 0 0 0 0 0];
DistanceRankingOrder=[2 3 4 5 6 7 8 9 1];
DirectionRankingOrder=[2 3 4 5 6 7 8 9 1];
RelevantParametersIndex=[false true true true true true true true true];
UnknownParamWeights=[3 2 0 0 0 0 0 0 0];
UnknownRankingOrder=[2 3 4 5 6 7 8 9 1];
%end script variables

assign_cells_to_tracks_functions=[];
else_is_empty_cells_label_functions=[];
if_is_empty_cells_label_functions=[];
image_read_loop_functions=[];
image_overlay_loop_functions=[];

loadtrackslayout.InstanceName='LoadTracksLayout';
loadtrackslayout.FunctionHandle=@loadTracksLayout;
loadtrackslayout.FunctionArgs.FileName.Value='tracks_layout.mat';
functions_list=addToFunctionChain(functions_list,loadtrackslayout);

loadancestrylayout.InstanceName='LoadAncestryLayout';
loadancestrylayout.FunctionHandle=@loadAncestryLayout;
loadancestrylayout.FunctionArgs.FileName.Value='ancestry_layout.mat';
functions_list=addToFunctionChain(functions_list,loadancestrylayout);

displaycurframe.InstanceName='DisplayCurFrame';
displaycurframe.FunctionHandle=@displayVariable;
displaycurframe.FunctionArgs.VariableName.Value='Current Tracking Frame';
displaycurframe.FunctionArgs.Variable.FunctionInstance='SegmentationLoop';
displaycurframe.FunctionArgs.Variable.OutputArg='LoopCounter';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,displaycurframe);

makeimagenamesinsegmentationloop.InstanceName='MakeImageNamesInSegmentationLoop';
makeimagenamesinsegmentationloop.FunctionHandle=@makeImgFileName;
makeimagenamesinsegmentationloop.FunctionArgs.FileBase.Value=ImageFileBase;
makeimagenamesinsegmentationloop.FunctionArgs.NumberFmt.Value=NumberFormat;
makeimagenamesinsegmentationloop.FunctionArgs.FileExt.Value=ImageExtension;
makeimagenamesinsegmentationloop.FunctionArgs.CurFrame.FunctionInstance='SegmentationLoop';
makeimagenamesinsegmentationloop.FunctionArgs.CurFrame.OutputArg='LoopCounter';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,makeimagenamesinsegmentationloop);

readimagesinsegmentationloop.InstanceName='ReadImagesInSegmentationLoop';
readimagesinsegmentationloop.FunctionHandle=@readImage;
readimagesinsegmentationloop.FunctionArgs.ImageChannel.Value='';
readimagesinsegmentationloop.FunctionArgs.ImageName.FunctionInstance='MakeImageNamesInSegmentationLoop';
readimagesinsegmentationloop.FunctionArgs.ImageName.OutputArg='FileName';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,readimagesinsegmentationloop);

normalizeimageto16bit.InstanceName='NormalizeImageTo16Bit';
normalizeimageto16bit.FunctionHandle=@imNorm;
normalizeimageto16bit.FunctionArgs.IntegerClass.Value='uint16';
normalizeimageto16bit.FunctionArgs.RawImage.FunctionInstance='ReadImagesInSegmentationLoop';
normalizeimageto16bit.FunctionArgs.RawImage.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,normalizeimageto16bit);

resizeimage.InstanceName='ResizeImage';
resizeimage.FunctionHandle=@resizeImage;
resizeimage.FunctionArgs.Scale.Value=ResizeImageScale;
resizeimage.FunctionArgs.Method.Value='bicubic';
resizeimage.FunctionArgs.Image.FunctionInstance='NormalizeImageTo16Bit';
resizeimage.FunctionArgs.Image.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,resizeimage);

cytogradientlocalfilter.InstanceName='CytoGradientLocalFilter';
cytogradientlocalfilter.FunctionHandle=@generateBinImgUsingGradient;
cytogradientlocalfilter.FunctionArgs.GradientThreshold.Value=GradientThreshold;
cytogradientlocalfilter.FunctionArgs.ClearBorder.Value=ClearBorder;
cytogradientlocalfilter.FunctionArgs.ClearBorderDist.Value=ClearBorderDist;
cytogradientlocalfilter.FunctionArgs.Image.FunctionInstance='ResizeImage';
cytogradientlocalfilter.FunctionArgs.Image.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,cytogradientlocalfilter);

fillholescytoplasmimages.InstanceName='FillHolesCytoplasmImages';
fillholescytoplasmimages.FunctionHandle=@fillHoles;
fillholescytoplasmimages.FunctionArgs.Image.FunctionInstance='CytoGradientLocalFilter';
fillholescytoplasmimages.FunctionArgs.Image.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,fillholescytoplasmimages);

clearsmallcells.InstanceName='ClearSmallCells';
clearsmallcells.FunctionHandle=@clearSmallObjects;
clearsmallcells.FunctionArgs.MinObjectArea.Value=ObjectArea;
clearsmallcells.FunctionArgs.Image.FunctionInstance='FillHolesCytoplasmImages';
clearsmallcells.FunctionArgs.Image.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,clearsmallcells);

nuclgradientlocalfilter.InstanceName='NuclGradientLocalFilter';
nuclgradientlocalfilter.FunctionHandle=@generateBinImgUsingGradient;
nuclgradientlocalfilter.FunctionArgs.GradientThreshold.Value=GradientThreshold;
nuclgradientlocalfilter.FunctionArgs.ClearBorder.Value=ClearBorder;
nuclgradientlocalfilter.FunctionArgs.ClearBorderDist.Value=ClearBorderDist;
nuclgradientlocalfilter.FunctionArgs.Image.FunctionInstance='ResizeImage';
nuclgradientlocalfilter.FunctionArgs.Image.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,nuclgradientlocalfilter);

fillholesnuclearimages.InstanceName='FillHolesNuclearImages';
fillholesnuclearimages.FunctionHandle=@fillHoles;
fillholesnuclearimages.FunctionArgs.Image.FunctionInstance='NuclGradientLocalFilter';
fillholesnuclearimages.FunctionArgs.Image.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,fillholesnuclearimages);

clearsmallnuclei.InstanceName='ClearSmallNuclei';
clearsmallnuclei.FunctionHandle=@clearSmallObjects;
clearsmallnuclei.FunctionArgs.MinObjectArea.Value=ObjectArea;
clearsmallnuclei.FunctionArgs.Image.FunctionInstance='FillHolesNuclearImages';
clearsmallnuclei.FunctionArgs.Image.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,clearsmallnuclei);

combinenuclearandcytoplasmimages.InstanceName='CombineNuclearAndCytoplasmImages';
combinenuclearandcytoplasmimages.FunctionHandle=@combineImages;
combinenuclearandcytoplasmimages.FunctionArgs.CombineOperation.Value='AND';
combinenuclearandcytoplasmimages.FunctionArgs.Image1.FunctionInstance='ClearSmallNuclei';
combinenuclearandcytoplasmimages.FunctionArgs.Image1.OutputArg='Image';
combinenuclearandcytoplasmimages.FunctionArgs.Image2.FunctionInstance='ClearSmallCells';
combinenuclearandcytoplasmimages.FunctionArgs.Image2.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,combinenuclearandcytoplasmimages);

reconstructcytoplasmimage.InstanceName='ReconstructCytoplasmImage';
reconstructcytoplasmimage.FunctionHandle=@reconstructObjects;
reconstructcytoplasmimage.FunctionArgs.GuideImage.FunctionInstance='CombineNuclearAndCytoplasmImages';
reconstructcytoplasmimage.FunctionArgs.GuideImage.OutputArg='Image';
reconstructcytoplasmimage.FunctionArgs.ImageToReconstruct.FunctionInstance='ClearSmallNuclei';
reconstructcytoplasmimage.FunctionArgs.ImageToReconstruct.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,reconstructcytoplasmimage);

labelnuclei.InstanceName='LabelNuclei';
labelnuclei.FunctionHandle=@labelObjects;
labelnuclei.FunctionArgs.Image.FunctionInstance='ClearSmallNuclei';
labelnuclei.FunctionArgs.Image.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,labelnuclei);

labelcytoplasm.InstanceName='LabelCytoplasm';
labelcytoplasm.FunctionHandle=@labelObjects;
labelcytoplasm.FunctionArgs.Image.FunctionInstance='ReconstructCytoplasmImage';
labelcytoplasm.FunctionArgs.Image.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,labelcytoplasm);

getconvexobjects.InstanceName='GetConvexObjects';
getconvexobjects.FunctionHandle=@getConvexObjects;
getconvexobjects.FunctionArgs.ApproximationDistance.Value=ApproximationDistance;
getconvexobjects.FunctionArgs.Image.FunctionInstance='ClearSmallNuclei';
getconvexobjects.FunctionArgs.Image.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,getconvexobjects);

segmentobjectsusingclusters.InstanceName='SegmentObjectsUsingClusters';
segmentobjectsusingclusters.FunctionHandle=@segmentObjectsUsingClusters;
segmentobjectsusingclusters.FunctionArgs.ObjectReduce.Value=ObjectReduce;
segmentobjectsusingclusters.FunctionArgs.MinimumObjectArea.Value=ObjectArea;
segmentobjectsusingclusters.FunctionArgs.ClusterDistance.Value=ClusterDist;
segmentobjectsusingclusters.FunctionArgs.ObjectsLabel.FunctionInstance='LabelNuclei';
segmentobjectsusingclusters.FunctionArgs.ObjectsLabel.OutputArg='LabelMatrix';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,segmentobjectsusingclusters);

segmentobjectsusingmarkers.InstanceName='SegmentObjectsUsingMarkers';
segmentobjectsusingmarkers.FunctionHandle=@segmentObjectsUsingMarkers;
segmentobjectsusingmarkers.FunctionArgs.MarkersLabel.FunctionInstance='SegmentObjectsUsingClusters';
segmentobjectsusingmarkers.FunctionArgs.MarkersLabel.OutputArg='LabelMatrix';
segmentobjectsusingmarkers.FunctionArgs.ObjectsLabel.FunctionInstance='LabelCytoplasm';
segmentobjectsusingmarkers.FunctionArgs.ObjectsLabel.OutputArg='LabelMatrix';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,segmentobjectsusingmarkers);

areafilter.InstanceName='AreaFilter';
areafilter.FunctionHandle=@areaFilterLabel;
areafilter.FunctionArgs.MinArea.Value=ObjectArea;
areafilter.FunctionArgs.ObjectsLabel.FunctionInstance='SegmentObjectsUsingMarkers';
areafilter.FunctionArgs.ObjectsLabel.OutputArg='LabelMatrix';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,areafilter);

resizecytolabel.InstanceName='ResizeCytoLabel';
resizecytolabel.FunctionHandle=@resizeImage;
resizecytolabel.FunctionArgs.Scale.Value=ResizeLabelMatrixScale;
resizecytolabel.FunctionArgs.Method.Value='nearest';
resizecytolabel.FunctionArgs.Image.FunctionInstance='AreaFilter';
resizecytolabel.FunctionArgs.Image.OutputArg='LabelMatrix';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,resizecytolabel);

getshapeparameters.InstanceName='GetShapeParameters';
getshapeparameters.FunctionHandle=@getShapeParams;
getshapeparameters.FunctionArgs.LabelMatrix.FunctionInstance='ResizeCytoLabel';
getshapeparameters.FunctionArgs.LabelMatrix.OutputArg='Image';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,getshapeparameters);

isemptypreviouscellslabel.InstanceName='IsEmptyPreviousCellsLabel';
isemptypreviouscellslabel.FunctionHandle=@isEmptyFunction;
isemptypreviouscellslabel.FunctionArgs.TestVariable.Value=[];
isemptypreviouscellslabel.FunctionArgs.TestVariable.FunctionInstance='SaveCellsLabel';
isemptypreviouscellslabel.FunctionArgs.TestVariable.OutputArg='CellsLabel';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,isemptypreviouscellslabel);

starttracks.InstanceName='StartTracks';
starttracks.FunctionHandle=@startTracks;
starttracks.FunctionArgs.TimeFrame.Value=TimeFrame;
starttracks.FunctionArgs.ShapeParameters.FunctionInstance='IfIsEmptyPreviousCellsLabel';
starttracks.FunctionArgs.ShapeParameters.InputArg='GetShapeParameters_ShapeParameters';
starttracks.FunctionArgs.CellsLabel.FunctionInstance='IfIsEmptyPreviousCellsLabel';
starttracks.FunctionArgs.CellsLabel.InputArg='ResizeCytoLabel_Image';
starttracks.FunctionArgs.CurFrame.FunctionInstance='IfIsEmptyPreviousCellsLabel';
starttracks.FunctionArgs.CurFrame.InputArg='SegmentationLoop_LoopCounter';
if_is_empty_cells_label_functions=addToFunctionChain(if_is_empty_cells_label_functions,starttracks);

getcurrenttracks.InstanceName='GetCurrentTracks';
getcurrenttracks.FunctionHandle=@getCurrentTracks;
getcurrenttracks.FunctionArgs.OffsetFrame.Value=-1;
getcurrenttracks.FunctionArgs.TimeFrame.Value=TimeFrame;
getcurrenttracks.FunctionArgs.TimeCol.Value=2;
getcurrenttracks.FunctionArgs.TrackIDCol.Value=1;
getcurrenttracks.FunctionArgs.MaxMissingFrames.Value=MaxFramesMissing;
getcurrenttracks.FunctionArgs.FrameStep.Value=FrameStep;
getcurrenttracks.FunctionArgs.Tracks.FunctionInstance='StartTracks';
getcurrenttracks.FunctionArgs.Tracks.OutputArg='Tracks';
getcurrenttracks.FunctionArgs.Tracks.FunctionInstance2='ContinueTracks';
getcurrenttracks.FunctionArgs.Tracks.OutputArg2='Tracks';
getcurrenttracks.FunctionArgs.CurFrame.FunctionInstance='IfIsEmptyPreviousCellsLabel';
getcurrenttracks.FunctionArgs.CurFrame.InputArg='SegmentationLoop_LoopCounter';
else_is_empty_cells_label_functions=addToFunctionChain(else_is_empty_cells_label_functions,getcurrenttracks);

getprevioustracks.InstanceName='GetPreviousTracks';
getprevioustracks.FunctionHandle=@getCurrentTracks;
getprevioustracks.FunctionArgs.OffsetFrame.Value=-2;
getprevioustracks.FunctionArgs.TimeFrame.Value=TimeFrame;
getprevioustracks.FunctionArgs.TimeCol.Value=2;
getprevioustracks.FunctionArgs.TrackIDCol.Value=1;
getprevioustracks.FunctionArgs.MaxMissingFrames.Value=MaxFramesMissing;
getprevioustracks.FunctionArgs.FrameStep.Value=FrameStep;
getprevioustracks.FunctionArgs.Tracks.FunctionInstance='StartTracks';
getprevioustracks.FunctionArgs.Tracks.OutputArg='Tracks';
getprevioustracks.FunctionArgs.Tracks.FunctionInstance2='ContinueTracks';
getprevioustracks.FunctionArgs.Tracks.OutputArg2='Tracks';
getprevioustracks.FunctionArgs.CurFrame.FunctionInstance='IfIsEmptyPreviousCellsLabel';
getprevioustracks.FunctionArgs.CurFrame.InputArg='SegmentationLoop_LoopCounter';
else_is_empty_cells_label_functions=addToFunctionChain(else_is_empty_cells_label_functions,getprevioustracks);

makeunassignedcellslist.InstanceName='MakeUnassignedCellsList';
makeunassignedcellslist.FunctionHandle=@makeUnassignedCellsList;
makeunassignedcellslist.FunctionArgs.CellsCentroids.FunctionInstance='IfIsEmptyPreviousCellsLabel';
makeunassignedcellslist.FunctionArgs.CellsCentroids.InputArg='GetShapeParameters_Centroids';
else_is_empty_cells_label_functions=addToFunctionChain(else_is_empty_cells_label_functions,makeunassignedcellslist);

makeexcludedtrackslist.InstanceName='MakeExcludedTracksList';
makeexcludedtrackslist.FunctionHandle=@makeExcludedTracksList;
makeexcludedtrackslist.FunctionArgs.UnassignedCellsIDs.FunctionInstance='MakeUnassignedCellsList';
makeexcludedtrackslist.FunctionArgs.UnassignedCellsIDs.OutputArg='UnassignedCellsIDs';
else_is_empty_cells_label_functions=addToFunctionChain(else_is_empty_cells_label_functions,makeexcludedtrackslist);

getcellsmeandisplacement.InstanceName='GetCellsMeanDisplacement';
getcellsmeandisplacement.FunctionHandle=@getObjectsMeanDisplacement;
getcellsmeandisplacement.FunctionArgs.Centroid1Col.Value=3;
getcellsmeandisplacement.FunctionArgs.Centroid2Col.Value=4;
getcellsmeandisplacement.FunctionArgs.CurrentTracks.FunctionInstance='GetCurrentTracks';
getcellsmeandisplacement.FunctionArgs.CurrentTracks.OutputArg='Tracks';
getcellsmeandisplacement.FunctionArgs.ObjectCentroids.FunctionInstance='IfIsEmptyPreviousCellsLabel';
getcellsmeandisplacement.FunctionArgs.ObjectCentroids.InputArg='GetShapeParameters_Centroids';
else_is_empty_cells_label_functions=addToFunctionChain(else_is_empty_cells_label_functions,getcellsmeandisplacement);

getparamscoefficientofvariation.InstanceName='GetParamsCoefficientOfVariation';
getparamscoefficientofvariation.FunctionHandle=@getParamsCoefficientOfVariation;
getparamscoefficientofvariation.FunctionArgs.AreaCol.Value=5;
getparamscoefficientofvariation.FunctionArgs.SolidityCol.Value=11;
getparamscoefficientofvariation.FunctionArgs.Params.FunctionInstance='IfIsEmptyPreviousCellsLabel';
getparamscoefficientofvariation.FunctionArgs.Params.InputArg='GetShapeParameters_ShapeParameters';
else_is_empty_cells_label_functions=addToFunctionChain(else_is_empty_cells_label_functions,getparamscoefficientofvariation);

getmaxtrackid.InstanceName='GetMaxTrackID';
getmaxtrackid.FunctionHandle=@getMaxTrackID;
getmaxtrackid.FunctionArgs.TrackIDCol.Value=1;
getmaxtrackid.FunctionArgs.Tracks.FunctionInstance='StartTracks';
getmaxtrackid.FunctionArgs.Tracks.OutputArg='Tracks';
getmaxtrackid.FunctionArgs.Tracks.FunctionInstance2='ContinueTracks';
getmaxtrackid.FunctionArgs.Tracks.OutputArg2='Tracks';
else_is_empty_cells_label_functions=addToFunctionChain(else_is_empty_cells_label_functions,getmaxtrackid);

isnotemptyunassignedcells.InstanceName='IsNotEmptyUnassignedCells';
isnotemptyunassignedcells.FunctionHandle=@isNotEmptyFunction;
isnotemptyunassignedcells.FunctionArgs.TestVariable.FunctionInstance='AssignCellToTrackUsingAll';
isnotemptyunassignedcells.FunctionArgs.TestVariable.OutputArg='UnassignedIDs';
isnotemptyunassignedcells.FunctionArgs.TestVariable.FunctionInstance2='AssignCellsToTracksLoop';
isnotemptyunassignedcells.FunctionArgs.TestVariable.InputArg2='MakeUnassignedCellsList_UnassignedCellsIDs';
assign_cells_to_tracks_functions=addToFunctionChain(assign_cells_to_tracks_functions,isnotemptyunassignedcells);

getcurrentunassignedcell.InstanceName='GetCurrentUnassignedCell';
getcurrentunassignedcell.FunctionHandle=@getCurrentUnassignedCell;
getcurrentunassignedcell.FunctionArgs.UnassignedCells.FunctionInstance='AssignCellToTrackUsingAll';
getcurrentunassignedcell.FunctionArgs.UnassignedCells.OutputArg='UnassignedIDs';
getcurrentunassignedcell.FunctionArgs.UnassignedCells.FunctionInstance2='AssignCellsToTracksLoop';
getcurrentunassignedcell.FunctionArgs.UnassignedCells.InputArg2='MakeUnassignedCellsList_UnassignedCellsIDs';
assign_cells_to_tracks_functions=addToFunctionChain(assign_cells_to_tracks_functions,getcurrentunassignedcell);

assigncelltotrackusingall.InstanceName='AssignCellToTrackUsingAll';
assigncelltotrackusingall.FunctionHandle=@assignCellToTrackUsingNN;
assigncelltotrackusingall.FunctionArgs.CheckCellPath.Value=false;
assigncelltotrackusingall.FunctionArgs.FrontParams.Value=FrontParams;
assigncelltotrackusingall.FunctionArgs.SearchRadiusPct.Value=SearchRadiusPct;
assigncelltotrackusingall.FunctionArgs.MaxSearchRadius.Value=MaxSearchRadius;
assigncelltotrackusingall.FunctionArgs.MinSearchRadius.Value=MinSearchRadius;
assigncelltotrackusingall.FunctionArgs.RelevantParametersIndex.Value=RelevantParametersIndex;
assigncelltotrackusingall.FunctionArgs.NrParamsForSureMatch.Value=NrParamsForSureMatch;
assigncelltotrackusingall.FunctionArgs.DefaultParamWeights.Value=DefaultParamWeights;
assigncelltotrackusingall.FunctionArgs.UnknownParamWeights.Value=UnknownParamWeights;
assigncelltotrackusingall.FunctionArgs.DistanceRankingOrder.Value=DistanceRankingOrder;
assigncelltotrackusingall.FunctionArgs.DirectionRankingOrder.Value=DirectionRankingOrder;
assigncelltotrackusingall.FunctionArgs.UnknownRankingOrder.Value=UnknownRankingOrder;
assigncelltotrackusingall.FunctionArgs.MinSecondDistance.Value=MinSecondDistance;
assigncelltotrackusingall.FunctionArgs.MaxDistRatio.Value=MaxDistRatio;
assigncelltotrackusingall.FunctionArgs.MaxAngleDiff.Value=MaxAngleDiff;
assigncelltotrackusingall.FunctionArgs.PreviousCellsLabel.Value=[];
assigncelltotrackusingall.FunctionArgs.TrackAssignments.Value=[];
assigncelltotrackusingall.FunctionArgs.Tracks.Value=[];
assigncelltotrackusingall.FunctionArgs.UnassignedCells.FunctionInstance='AssignCellToTrackUsingAll';
assigncelltotrackusingall.FunctionArgs.UnassignedCells.OutputArg='UnassignedIDs';
assigncelltotrackusingall.FunctionArgs.ExcludedTracks.FunctionInstance='AssignCellToTrackUsingAll';
assigncelltotrackusingall.FunctionArgs.ExcludedTracks.OutputArg='ExcludedTracks';
assigncelltotrackusingall.FunctionArgs.TrackAssignments.FunctionInstance='AssignCellToTrackUsingAll';
assigncelltotrackusingall.FunctionArgs.TrackAssignments.OutputArg='TrackAssignments';
assigncelltotrackusingall.FunctionArgs.UnassignedCells.FunctionInstance2='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.UnassignedCells.InputArg2='MakeUnassignedCellsList_UnassignedCellsIDs';
assigncelltotrackusingall.FunctionArgs.ExcludedTracks.FunctionInstance2='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.ExcludedTracks.InputArg2='MakeExcludedTracksList_ExcludedTracks';
assigncelltotrackusingall.FunctionArgs.CellsLabel.FunctionInstance='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.CellsLabel.InputArg='ResizeCytoLabel_Image';
assigncelltotrackusingall.FunctionArgs.PreviousCellsLabel.FunctionInstance='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.PreviousCellsLabel.InputArg='SaveCellsLabel_CellsLabel';
assigncelltotrackusingall.FunctionArgs.ShapeParameters.FunctionInstance='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.ShapeParameters.InputArg='GetShapeParameters_ShapeParameters';
assigncelltotrackusingall.FunctionArgs.CellsCentroids.FunctionInstance='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.CellsCentroids.InputArg='GetShapeParameters_Centroids';
assigncelltotrackusingall.FunctionArgs.CurrentTracks.FunctionInstance='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.CurrentTracks.InputArg='GetCurrentTracks_Tracks';
assigncelltotrackusingall.FunctionArgs.MaxTrackID.FunctionInstance='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.MaxTrackID.InputArg='GetMaxTrackID_MaxTrackID';
assigncelltotrackusingall.FunctionArgs.Tracks.FunctionInstance='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.Tracks.InputArg='SegmentationLoop_Tracks';
assigncelltotrackusingall.FunctionArgs.PreviousTracks.FunctionInstance='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.PreviousTracks.InputArg='GetPreviousTracks_Tracks';
assigncelltotrackusingall.FunctionArgs.TracksLayout.FunctionInstance='AssignCellsToTracksLoop';
assigncelltotrackusingall.FunctionArgs.TracksLayout.InputArg='LoadTracksLayout_TracksLayout';
assign_cells_to_tracks_functions=addToFunctionChain(assign_cells_to_tracks_functions,assigncelltotrackusingall);

assigncellstotracksloop.InstanceName='AssignCellsToTracksLoop';
assigncellstotracksloop.FunctionHandle=@whileLoop;
assigncellstotracksloop.FunctionArgs.TestFunction.FunctionInstance='IsNotEmptyUnassignedCells';
assigncellstotracksloop.FunctionArgs.TestFunction.OutputArg='Boolean';
assigncellstotracksloop.FunctionArgs.MakeUnassignedCellsList_UnassignedCellsIDs.FunctionInstance='MakeUnassignedCellsList';
assigncellstotracksloop.FunctionArgs.MakeUnassignedCellsList_UnassignedCellsIDs.OutputArg='UnassignedCellsIDs';
assigncellstotracksloop.FunctionArgs.MakeExcludedTracksList_ExcludedTracks.FunctionInstance='MakeExcludedTracksList';
assigncellstotracksloop.FunctionArgs.MakeExcludedTracksList_ExcludedTracks.OutputArg='ExcludedTracks';
assigncellstotracksloop.FunctionArgs.GetCurrentTracks_Tracks.FunctionInstance='GetCurrentTracks';
assigncellstotracksloop.FunctionArgs.GetCurrentTracks_Tracks.OutputArg='Tracks';
assigncellstotracksloop.FunctionArgs.GetMaxTrackID_MaxTrackID.FunctionInstance='GetMaxTrackID';
assigncellstotracksloop.FunctionArgs.GetMaxTrackID_MaxTrackID.OutputArg='MaxTrackID';
assigncellstotracksloop.FunctionArgs.GetPreviousTracks_Tracks.FunctionInstance='GetPreviousTracks';
assigncellstotracksloop.FunctionArgs.GetPreviousTracks_Tracks.OutputArg='Tracks';
assigncellstotracksloop.FunctionArgs.ResizeCytoLabel_Image.FunctionInstance='IfIsEmptyPreviousCellsLabel';
assigncellstotracksloop.FunctionArgs.ResizeCytoLabel_Image.InputArg='ResizeCytoLabel_Image';
assigncellstotracksloop.FunctionArgs.SaveCellsLabel_CellsLabel.FunctionInstance='IfIsEmptyPreviousCellsLabel';
assigncellstotracksloop.FunctionArgs.SaveCellsLabel_CellsLabel.InputArg='SaveCellsLabel_CellsLabel';
assigncellstotracksloop.FunctionArgs.GetShapeParameters_ShapeParameters.FunctionInstance='IfIsEmptyPreviousCellsLabel';
assigncellstotracksloop.FunctionArgs.GetShapeParameters_ShapeParameters.InputArg='GetShapeParameters_ShapeParameters';
assigncellstotracksloop.FunctionArgs.GetShapeParameters_Centroids.FunctionInstance='IfIsEmptyPreviousCellsLabel';
assigncellstotracksloop.FunctionArgs.GetShapeParameters_Centroids.InputArg='GetShapeParameters_Centroids';
assigncellstotracksloop.FunctionArgs.SegmentationLoop_Tracks.FunctionInstance='IfIsEmptyPreviousCellsLabel';
assigncellstotracksloop.FunctionArgs.SegmentationLoop_Tracks.InputArg='SegmentationLoop_Tracks';
assigncellstotracksloop.FunctionArgs.LoadTracksLayout_TracksLayout.FunctionInstance='IfIsEmptyPreviousCellsLabel';
assigncellstotracksloop.FunctionArgs.LoadTracksLayout_TracksLayout.InputArg='LoadTracksLayout_TracksLayout';
assigncellstotracksloop.KeepValues.AssignCellToTrackUsingAll_TrackAssignments.FunctionInstance='AssignCellToTrackUsingAll';
assigncellstotracksloop.KeepValues.AssignCellToTrackUsingAll_TrackAssignments.OutputArg='TrackAssignments';
assigncellstotracksloop.LoopFunctions=assign_cells_to_tracks_functions;
else_is_empty_cells_label_functions=addToFunctionChain(else_is_empty_cells_label_functions,assigncellstotracksloop);

continuetracks.InstanceName='ContinueTracks';
continuetracks.FunctionHandle=@continueTracks;
continuetracks.FunctionArgs.TimeFrame.Value=TimeFrame;
continuetracks.FunctionArgs.Tracks.FunctionInstance='StartTracks';
continuetracks.FunctionArgs.Tracks.OutputArg='Tracks';
continuetracks.FunctionArgs.Tracks.FunctionInstance2='ContinueTracks';
continuetracks.FunctionArgs.Tracks.OutputArg2='Tracks';
continuetracks.FunctionArgs.TrackAssignments.FunctionInstance='AssignCellsToTracksLoop';
continuetracks.FunctionArgs.TrackAssignments.OutputArg='AssignCellToTrackUsingAll_TrackAssignments';
continuetracks.FunctionArgs.CellsCentroids.FunctionInstance='IfIsEmptyPreviousCellsLabel';
continuetracks.FunctionArgs.CellsCentroids.InputArg='GetShapeParameters_Centroids';
continuetracks.FunctionArgs.ShapeParameters.FunctionInstance='IfIsEmptyPreviousCellsLabel';
continuetracks.FunctionArgs.ShapeParameters.InputArg='GetShapeParameters_ShapeParameters';
continuetracks.FunctionArgs.CurFrame.FunctionInstance='IfIsEmptyPreviousCellsLabel';
continuetracks.FunctionArgs.CurFrame.InputArg='SegmentationLoop_LoopCounter';
else_is_empty_cells_label_functions=addToFunctionChain(else_is_empty_cells_label_functions,continuetracks);

ifisemptypreviouscellslabel.InstanceName='IfIsEmptyPreviousCellsLabel';
ifisemptypreviouscellslabel.FunctionHandle=@if_statement;
ifisemptypreviouscellslabel.FunctionArgs.PreviousCellsLabel.Value=[];
ifisemptypreviouscellslabel.FunctionArgs.Tracks.Value=[];
ifisemptypreviouscellslabel.FunctionArgs.TrackAssignments.Value=[];
ifisemptypreviouscellslabel.FunctionArgs.TestVariable.FunctionInstance='IsEmptyPreviousCellsLabel';
ifisemptypreviouscellslabel.FunctionArgs.TestVariable.OutputArg='Boolean';
ifisemptypreviouscellslabel.FunctionArgs.GetShapeParameters_ShapeParameters.FunctionInstance='GetShapeParameters';
ifisemptypreviouscellslabel.FunctionArgs.GetShapeParameters_ShapeParameters.OutputArg='ShapeParameters';
ifisemptypreviouscellslabel.FunctionArgs.ResizeCytoLabel_Image.FunctionInstance='ResizeCytoLabel';
ifisemptypreviouscellslabel.FunctionArgs.ResizeCytoLabel_Image.OutputArg='Image';
ifisemptypreviouscellslabel.FunctionArgs.SegmentationLoop_LoopCounter.FunctionInstance='SegmentationLoop';
ifisemptypreviouscellslabel.FunctionArgs.SegmentationLoop_LoopCounter.OutputArg='LoopCounter';
ifisemptypreviouscellslabel.FunctionArgs.GetShapeParameters_Centroids.FunctionInstance='GetShapeParameters';
ifisemptypreviouscellslabel.FunctionArgs.GetShapeParameters_Centroids.OutputArg='Centroids';
ifisemptypreviouscellslabel.FunctionArgs.SaveCellsLabel_CellsLabel.FunctionInstance='SaveCellsLabel';
ifisemptypreviouscellslabel.FunctionArgs.SaveCellsLabel_CellsLabel.OutputArg='CellsLabel';
ifisemptypreviouscellslabel.FunctionArgs.SegmentationLoop_Tracks.FunctionInstance='SegmentationLoop';
ifisemptypreviouscellslabel.FunctionArgs.SegmentationLoop_Tracks.OutputArg='Tracks';
ifisemptypreviouscellslabel.FunctionArgs.LoadTracksLayout_TracksLayout.FunctionInstance='SegmentationLoop';
ifisemptypreviouscellslabel.FunctionArgs.LoadTracksLayout_TracksLayout.InputArg='LoadTracksLayout_TracksLayout';
ifisemptypreviouscellslabel.KeepValues.ContinueTracks_Tracks.FunctionInstance='ContinueTracks';
ifisemptypreviouscellslabel.KeepValues.ContinueTracks_Tracks.OutputArg='Tracks';
ifisemptypreviouscellslabel.ElseFunctions=else_is_empty_cells_label_functions;
ifisemptypreviouscellslabel.IfFunctions=if_is_empty_cells_label_functions;
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,ifisemptypreviouscellslabel);

savecellslabel.InstanceName='SaveCellsLabel';
savecellslabel.FunctionHandle=@saveCellsLabel;
savecellslabel.FunctionArgs.FileRoot.Value=SegmentationFilesRoot;
savecellslabel.FunctionArgs.NumberFormat.Value=NumberFormat;
savecellslabel.FunctionArgs.CellsLabel.FunctionInstance='ResizeCytoLabel';
savecellslabel.FunctionArgs.CellsLabel.OutputArg='Image';
savecellslabel.FunctionArgs.CurFrame.FunctionInstance='SegmentationLoop';
savecellslabel.FunctionArgs.CurFrame.OutputArg='LoopCounter';
image_read_loop_functions=addToFunctionChain(image_read_loop_functions,savecellslabel);

segmentationloop.InstanceName='SegmentationLoop';
segmentationloop.FunctionHandle=@forLoop;
segmentationloop.FunctionArgs.StartLoop.Value=StartFrame;
segmentationloop.FunctionArgs.EndLoop.Value=(StartFrame+FrameCount-1)*FrameStep;
segmentationloop.FunctionArgs.IncrementLoop.Value=FrameStep;
segmentationloop.FunctionArgs.Tracks.Value=[];
segmentationloop.FunctionArgs.LoadTracksLayout_TracksLayout.FunctionInstance='LoadTracksLayout';
segmentationloop.FunctionArgs.LoadTracksLayout_TracksLayout.OutputArg='TracksLayout';
segmentationloop.KeepValues.ContinueTracks_Tracks.FunctionInstance='IfIsEmptyPreviousCellsLabel';
segmentationloop.KeepValues.ContinueTracks_Tracks.OutputArg='ContinueTracks_Tracks';
segmentationloop.LoopFunctions=image_read_loop_functions;
functions_list=addToFunctionChain(functions_list,segmentationloop);

savetracks.InstanceName='SaveTracks';
savetracks.FunctionHandle=@saveTracks;
savetracks.FunctionArgs.TracksFileName.Value=[TracksFolder '/tracks.mat'];
savetracks.FunctionArgs.Tracks.FunctionInstance='SegmentationLoop';
savetracks.FunctionArgs.Tracks.OutputArg='ContinueTracks_Tracks';
functions_list=addToFunctionChain(functions_list,savetracks);

gettrackids.InstanceName='GetTrackIDs';
gettrackids.FunctionHandle=@getTrackIDs;
gettrackids.FunctionArgs.TrackIDCol.Value=1;
gettrackids.FunctionArgs.Tracks.FunctionInstance='SegmentationLoop';
gettrackids.FunctionArgs.Tracks.OutputArg='ContinueTracks_Tracks';
functions_list=addToFunctionChain(functions_list,gettrackids);

detectmergecandidates.InstanceName='DetectMergeCandidates';
detectmergecandidates.FunctionHandle=@detectMergeCandidatesUsingDistance;
detectmergecandidates.FunctionArgs.MaxMergeDistance.Value=MaxMergeDistance;
detectmergecandidates.FunctionArgs.TrackIDs.FunctionInstance='GetTrackIDs';
detectmergecandidates.FunctionArgs.TrackIDs.OutputArg='TrackIDs';
detectmergecandidates.FunctionArgs.TracksLayout.FunctionInstance='LoadTracksLayout';
detectmergecandidates.FunctionArgs.TracksLayout.OutputArg='TracksLayout';
detectmergecandidates.FunctionArgs.Tracks.FunctionInstance='SegmentationLoop';
detectmergecandidates.FunctionArgs.Tracks.OutputArg='ContinueTracks_Tracks';
functions_list=addToFunctionChain(functions_list,detectmergecandidates);

mergetracks.InstanceName='MergeTracks';
mergetracks.FunctionHandle=@mergeTracks;
mergetracks.FunctionArgs.FrameCount.Value=FrameCount;
mergetracks.FunctionArgs.StartFrame.Value=StartFrame;
mergetracks.FunctionArgs.TimeFrame.Value=TimeFrame;
mergetracks.FunctionArgs.SegFileRoot.Value=SegmentationFilesRoot;
mergetracks.FunctionArgs.FrameStep.Value=FrameStep;
mergetracks.FunctionArgs.NumberFormat.Value=NumberFormat;
mergetracks.FunctionArgs.TracksToBeMerged.FunctionInstance='DetectMergeCandidates';
mergetracks.FunctionArgs.TracksToBeMerged.OutputArg='TracksToBeMerged';
mergetracks.FunctionArgs.TracksLayout.FunctionInstance='LoadTracksLayout';
mergetracks.FunctionArgs.TracksLayout.OutputArg='TracksLayout';
mergetracks.FunctionArgs.Tracks.FunctionInstance='SegmentationLoop';
mergetracks.FunctionArgs.Tracks.OutputArg='ContinueTracks_Tracks';
functions_list=addToFunctionChain(functions_list,mergetracks);

gettrackidsaftermerge.InstanceName='GetTrackIDsAfterMerge';
gettrackidsaftermerge.FunctionHandle=@getTrackIDs;
gettrackidsaftermerge.FunctionArgs.TrackIDCol.Value=1;
gettrackidsaftermerge.FunctionArgs.Tracks.FunctionInstance='MergeTracks';
gettrackidsaftermerge.FunctionArgs.Tracks.OutputArg='Tracks';
functions_list=addToFunctionChain(functions_list,gettrackidsaftermerge);

makeancestryforfirstframecells.InstanceName='MakeAncestryForFirstFrameCells';
makeancestryforfirstframecells.FunctionHandle=@makeAncestryForFirstFrameCells;
makeancestryforfirstframecells.FunctionArgs.TimeCol.Value=2;
makeancestryforfirstframecells.FunctionArgs.TrackIDCol.Value=1;
makeancestryforfirstframecells.FunctionArgs.Tracks.FunctionInstance='MergeTracks';
makeancestryforfirstframecells.FunctionArgs.Tracks.OutputArg='Tracks';
makeancestryforfirstframecells.FunctionArgs.TrackIDs.FunctionInstance='GetTrackIDsAfterMerge';
makeancestryforfirstframecells.FunctionArgs.TrackIDs.OutputArg='TrackIDs';
functions_list=addToFunctionChain(functions_list,makeancestryforfirstframecells);

detectmitoticevents.InstanceName='DetectMitoticEvents';
detectmitoticevents.FunctionHandle=@detectMitoticEvents;
detectmitoticevents.FunctionArgs.MaxSplitArea.Value=MaxSplitArea;
detectmitoticevents.FunctionArgs.MinSplitEccentricity.Value=MinSplitEccentricity;
detectmitoticevents.FunctionArgs.MaxSplitEccentricity.Value=MaxSplitEccentricity;
detectmitoticevents.FunctionArgs.MaxSplitDistance.Value=MaxSplitDistance;
detectmitoticevents.FunctionArgs.MinTimeForSplit.Value=MinTimeForSplit;
detectmitoticevents.FunctionArgs.Tracks.FunctionInstance='MergeTracks';
detectmitoticevents.FunctionArgs.Tracks.OutputArg='Tracks';
detectmitoticevents.FunctionArgs.UntestedIDs.FunctionInstance='MakeAncestryForFirstFrameCells';
detectmitoticevents.FunctionArgs.UntestedIDs.OutputArg='UntestedIDs';
detectmitoticevents.FunctionArgs.TracksLayout.FunctionInstance='LoadTracksLayout';
detectmitoticevents.FunctionArgs.TracksLayout.OutputArg='TracksLayout';
functions_list=addToFunctionChain(functions_list,detectmitoticevents);

makeancestryforcellsenteringframes.InstanceName='MakeAncestryForCellsEnteringFrames';
makeancestryforcellsenteringframes.FunctionHandle=@makeAncestryForCellsEnteringFrames;
makeancestryforcellsenteringframes.FunctionArgs.TimeCol.Value=2;
makeancestryforcellsenteringframes.FunctionArgs.TrackIDCol.Value=1;
makeancestryforcellsenteringframes.FunctionArgs.SplitCells.FunctionInstance='DetectMitoticEvents';
makeancestryforcellsenteringframes.FunctionArgs.SplitCells.OutputArg='SplitCells';
makeancestryforcellsenteringframes.FunctionArgs.TrackIDs.FunctionInstance='GetTrackIDsAfterMerge';
makeancestryforcellsenteringframes.FunctionArgs.TrackIDs.OutputArg='TrackIDs';
makeancestryforcellsenteringframes.FunctionArgs.FirstFrameIDs.FunctionInstance='MakeAncestryForFirstFrameCells';
makeancestryforcellsenteringframes.FunctionArgs.FirstFrameIDs.OutputArg='FirstFrameIDs';
makeancestryforcellsenteringframes.FunctionArgs.CellsAncestry.FunctionInstance='MakeAncestryForFirstFrameCells';
makeancestryforcellsenteringframes.FunctionArgs.CellsAncestry.OutputArg='CellsAncestry';
makeancestryforcellsenteringframes.FunctionArgs.Tracks.FunctionInstance='MergeTracks';
makeancestryforcellsenteringframes.FunctionArgs.Tracks.OutputArg='Tracks';
functions_list=addToFunctionChain(functions_list,makeancestryforcellsenteringframes);

splittracks.InstanceName='SplitTracks';
splittracks.FunctionHandle=@splitTracks;
splittracks.FunctionArgs.TimeFrame.Value=TimeFrame;
splittracks.FunctionArgs.SplitCells.FunctionInstance='DetectMitoticEvents';
splittracks.FunctionArgs.SplitCells.OutputArg='SplitCells';
splittracks.FunctionArgs.Tracks.FunctionInstance='MergeTracks';
splittracks.FunctionArgs.Tracks.OutputArg='Tracks';
splittracks.FunctionArgs.CellsAncestry.FunctionInstance='MakeAncestryForCellsEnteringFrames';
splittracks.FunctionArgs.CellsAncestry.OutputArg='CellsAncestry';
splittracks.FunctionArgs.TracksLayout.FunctionInstance='LoadTracksLayout';
splittracks.FunctionArgs.TracksLayout.OutputArg='TracksLayout';
splittracks.FunctionArgs.AncestryLayout.FunctionInstance='LoadAncestryLayout';
splittracks.FunctionArgs.AncestryLayout.OutputArg='AncestryLayout';
functions_list=addToFunctionChain(functions_list,splittracks);

removeshorttracks.InstanceName='RemoveShortTracks';
removeshorttracks.FunctionHandle=@removeShortTracks;
removeshorttracks.FunctionArgs.MinLifespan.Value=MinLifespan;
removeshorttracks.FunctionArgs.Tracks.FunctionInstance='SplitTracks';
removeshorttracks.FunctionArgs.Tracks.OutputArg='Tracks';
removeshorttracks.FunctionArgs.CellsAncestry.FunctionInstance='SplitTracks';
removeshorttracks.FunctionArgs.CellsAncestry.OutputArg='CellsAncestry';
removeshorttracks.FunctionArgs.TracksLayout.FunctionInstance='LoadTracksLayout';
removeshorttracks.FunctionArgs.TracksLayout.OutputArg='TracksLayout';
removeshorttracks.FunctionArgs.AncestryLayout.FunctionInstance='LoadAncestryLayout';
removeshorttracks.FunctionArgs.AncestryLayout.OutputArg='AncestryLayout';
functions_list=addToFunctionChain(functions_list,removeshorttracks);

saveupdatedtracks.InstanceName='SaveUpdatedTracks';
saveupdatedtracks.FunctionHandle=@saveTracks;
saveupdatedtracks.FunctionArgs.TracksFileName.Value=[AncestryFolder '/tracks.mat'];
saveupdatedtracks.FunctionArgs.Tracks.FunctionInstance='RemoveShortTracks';
saveupdatedtracks.FunctionArgs.Tracks.OutputArg='Tracks';
functions_list=addToFunctionChain(functions_list,saveupdatedtracks);

saveancestry.InstanceName='SaveAncestry';
saveancestry.FunctionHandle=@saveAncestry;
saveancestry.FunctionArgs.AncestryFileName.Value=[AncestryFolder '/ancestry.mat'];
saveancestry.FunctionArgs.CellsAncestry.FunctionInstance='RemoveShortTracks';
saveancestry.FunctionArgs.CellsAncestry.OutputArg='CellsAncestry';
functions_list=addToFunctionChain(functions_list,saveancestry);

makeimagenamesinoverlayloop.InstanceName='MakeImageNamesInOverlayLoop';
makeimagenamesinoverlayloop.FunctionHandle=@makeImgFileName;
makeimagenamesinoverlayloop.FunctionArgs.FileBase.Value=ImageFileBase;
makeimagenamesinoverlayloop.FunctionArgs.NumberFmt.Value=NumberFormat;
makeimagenamesinoverlayloop.FunctionArgs.FileExt.Value=ImageExtension;
makeimagenamesinoverlayloop.FunctionArgs.CurFrame.FunctionInstance='ImageOverlayLoop';
makeimagenamesinoverlayloop.FunctionArgs.CurFrame.OutputArg='LoopCounter';
image_overlay_loop_functions=addToFunctionChain(image_overlay_loop_functions,makeimagenamesinoverlayloop);

readimagesinoverlayloop.InstanceName='ReadImagesInOverlayLoop';
readimagesinoverlayloop.FunctionHandle=@readImage;
readimagesinoverlayloop.FunctionArgs.ImageChannel.Value='';
readimagesinoverlayloop.FunctionArgs.ImageName.FunctionInstance='MakeImageNamesInOverlayLoop';
readimagesinoverlayloop.FunctionArgs.ImageName.OutputArg='FileName';
image_overlay_loop_functions=addToFunctionChain(image_overlay_loop_functions,readimagesinoverlayloop);

getcurrenttracks2.InstanceName='GetCurrentTracks2';
getcurrenttracks2.FunctionHandle=@getCurrentTracks;
getcurrenttracks2.FunctionArgs.OffsetFrame.Value=0;
getcurrenttracks2.FunctionArgs.TimeFrame.Value=TimeFrame;
getcurrenttracks2.FunctionArgs.TimeCol.Value=2;
getcurrenttracks2.FunctionArgs.TrackIDCol.Value=1;
getcurrenttracks2.FunctionArgs.MaxMissingFrames.Value=MaxFramesMissing;
getcurrenttracks2.FunctionArgs.FrameStep.Value=FrameStep;
getcurrenttracks2.FunctionArgs.CurFrame.FunctionInstance='ImageOverlayLoop';
getcurrenttracks2.FunctionArgs.CurFrame.OutputArg='LoopCounter';
getcurrenttracks2.FunctionArgs.Tracks.FunctionInstance='ImageOverlayLoop';
getcurrenttracks2.FunctionArgs.Tracks.InputArg='RemoveShortTracks_Tracks';
image_overlay_loop_functions=addToFunctionChain(image_overlay_loop_functions,getcurrenttracks2);

makematnamesinoverlayloop.InstanceName='MakeMatNamesInOverlayLoop';
makematnamesinoverlayloop.FunctionHandle=@makeImgFileName;
makematnamesinoverlayloop.FunctionArgs.FileBase.Value=SegmentationFilesRoot;
makematnamesinoverlayloop.FunctionArgs.NumberFmt.Value=NumberFormat;
makematnamesinoverlayloop.FunctionArgs.FileExt.Value='.mat';
makematnamesinoverlayloop.FunctionArgs.CurFrame.FunctionInstance='ImageOverlayLoop';
makematnamesinoverlayloop.FunctionArgs.CurFrame.OutputArg='LoopCounter';
image_overlay_loop_functions=addToFunctionChain(image_overlay_loop_functions,makematnamesinoverlayloop);

loadcellslabel.InstanceName='LoadCellsLabel';
loadcellslabel.FunctionHandle=@loadCellsLabel;
loadcellslabel.FunctionArgs.FileName.FunctionInstance='MakeMatNamesInOverlayLoop';
loadcellslabel.FunctionArgs.FileName.OutputArg='FileName';
image_overlay_loop_functions=addToFunctionChain(image_overlay_loop_functions,loadcellslabel);

loadcolormap.InstanceName='LoadColormap';
loadcolormap.FunctionHandle=@loadColormap;
loadcolormap.FunctionArgs.FileName.Value='colormap_lines';
image_overlay_loop_functions=addToFunctionChain(image_overlay_loop_functions,loadcolormap);

displayoverlayingframe.InstanceName='DisplayOverlayingFrame';
displayoverlayingframe.FunctionHandle=@displayVariable;
displayoverlayingframe.FunctionArgs.VariableName.Value='Overlaying Frame';
displayoverlayingframe.FunctionArgs.Variable.FunctionInstance='ImageOverlayLoop';
displayoverlayingframe.FunctionArgs.Variable.OutputArg='LoopCounter';
image_overlay_loop_functions=addToFunctionChain(image_overlay_loop_functions,displayoverlayingframe);

displayancestry.InstanceName='DisplayAncestry';
displayancestry.FunctionHandle=@displayAncestryData;
displayancestry.FunctionArgs.NumberFormat.Value=NumberFormat;
displayancestry.FunctionArgs.ProlDir.Value=AncestryFolder;
displayancestry.FunctionArgs.ImageFileName.Value=ImageFilesRoot;
displayancestry.FunctionArgs.DS.Value='/';
displayancestry.FunctionArgs.Image.FunctionInstance='ReadImagesInOverlayLoop';
displayancestry.FunctionArgs.Image.OutputArg='Image';
displayancestry.FunctionArgs.CurrentTracks.FunctionInstance='GetCurrentTracks2';
displayancestry.FunctionArgs.CurrentTracks.OutputArg='Tracks';
displayancestry.FunctionArgs.CellsLabel.FunctionInstance='LoadCellsLabel';
displayancestry.FunctionArgs.CellsLabel.OutputArg='LabelMatrix';
displayancestry.FunctionArgs.CurFrame.FunctionInstance='ImageOverlayLoop';
displayancestry.FunctionArgs.CurFrame.OutputArg='LoopCounter';
displayancestry.FunctionArgs.ColorMap.FunctionInstance='LoadColormap';
displayancestry.FunctionArgs.ColorMap.OutputArg='Colormap';
displayancestry.FunctionArgs.CellsAncestry.FunctionInstance='ImageOverlayLoop';
displayancestry.FunctionArgs.CellsAncestry.InputArg='RemoveShortTracks_CellsAncestry';
displayancestry.FunctionArgs.TracksLayout.FunctionInstance='ImageOverlayLoop';
displayancestry.FunctionArgs.TracksLayout.InputArg='LoadTracksLayout_TracksLayout';
displayancestry.FunctionArgs.AncestryLayout.FunctionInstance='ImageOverlayLoop';
displayancestry.FunctionArgs.AncestryLayout.InputArg='LoadAncestryLayout_AncestryLayout';
image_overlay_loop_functions=addToFunctionChain(image_overlay_loop_functions,displayancestry);

imageoverlayloop.InstanceName='ImageOverlayLoop';
imageoverlayloop.FunctionHandle=@forLoop;
imageoverlayloop.FunctionArgs.StartLoop.Value=StartFrame;
imageoverlayloop.FunctionArgs.EndLoop.Value=(StartFrame+FrameCount-1)*FrameStep;
imageoverlayloop.FunctionArgs.IncrementLoop.Value=FrameStep;
imageoverlayloop.FunctionArgs.RemoveShortTracks_Tracks.FunctionInstance='RemoveShortTracks';
imageoverlayloop.FunctionArgs.RemoveShortTracks_Tracks.OutputArg='Tracks';
imageoverlayloop.FunctionArgs.RemoveShortTracks_CellsAncestry.FunctionInstance='RemoveShortTracks';
imageoverlayloop.FunctionArgs.RemoveShortTracks_CellsAncestry.OutputArg='CellsAncestry';
imageoverlayloop.FunctionArgs.LoadTracksLayout_TracksLayout.FunctionInstance='LoadTracksLayout';
imageoverlayloop.FunctionArgs.LoadTracksLayout_TracksLayout.OutputArg='TracksLayout';
imageoverlayloop.FunctionArgs.LoadAncestryLayout_AncestryLayout.FunctionInstance='LoadAncestryLayout';
imageoverlayloop.FunctionArgs.LoadAncestryLayout_AncestryLayout.OutputArg='AncestryLayout';
imageoverlayloop.LoopFunctions=image_overlay_loop_functions;
functions_list=addToFunctionChain(functions_list,imageoverlayloop);

saveancestryspreadsheets.InstanceName='SaveAncestrySpreadsheets';
saveancestryspreadsheets.FunctionHandle=@saveAncestrySpreadsheets;
saveancestryspreadsheets.FunctionArgs.ShapesXlsFile.Value=ShapesSpreadsheet;
saveancestryspreadsheets.FunctionArgs.ProlXlsFile.Value=AncestrySpreadsheet;
saveancestryspreadsheets.FunctionArgs.Tracks.FunctionInstance='RemoveShortTracks';
saveancestryspreadsheets.FunctionArgs.Tracks.OutputArg='Tracks';
saveancestryspreadsheets.FunctionArgs.CellsAncestry.FunctionInstance='RemoveShortTracks';
saveancestryspreadsheets.FunctionArgs.CellsAncestry.OutputArg='CellsAncestry';
saveancestryspreadsheets.FunctionArgs.TracksLayout.FunctionInstance='LoadTracksLayout';
saveancestryspreadsheets.FunctionArgs.TracksLayout.OutputArg='TracksLayout';
functions_list=addToFunctionChain(functions_list,saveancestryspreadsheets);


global dependencies_list;
global dependencies_index;
dependencies_list={};
dependencies_index=java.util.Hashtable;
makeDependencies([]);
runFunctions();
end