function output_args=loadShapeParams(input_args)

im_num_str=sprintf(input_args.num_format.Value, input_args.CurFrame.Value);
load([input_args.directory.Value filesep ...
	  input_args.image_name_base.Value im_num_str '.mat']);
shape_params = [[objSet.props.Area]' ...
				[objSet.props.Eccentricity]' ...
			    [objSet.props.MajorAxisLength]' ...
				[objSet.props.MinorAxisLength]' ...
				[objSet.props.Orientation]'+90 ...
				[objSet.props.Perimeter]' ...
				[objSet.props.Solidity]' ...
				[objSet.props.label]' ...
				zeros(size(objSet.props))];
output_args.ShapeParameters=shape_params;
cells_centroids=[objSet.props.Centroid]';
centr_len=size(cells_centroids,1);
cells_centroids=[cells_centroids(2:2:centr_len) cells_centroids(1:2:centr_len)];
output_args.Centroids=cells_centroids;

end
