function SaveWellFromOmero(destination, wellid, startIndex, endIndex, ...
						   imageNameBase, digitsForEnum)

  [client, session, gateway] = ConnectToOmero();

  for(i=startIndex:endIndex)
    imNumStr = int2str(10^(digitsForEnum-1) + i);
    imNumStr(1) = '0'
    SaveImageFromOmero(gateway, ... 
					   wellid, ...
					   i, ...
					   [destination filesep ...
					      imageNameBase imNumStr '.tif'], ...
					   'tif');
  end

end
