#!/bin/bash
#PBS -M samuel.w.hooke@vanderbilt.edu
#PBS -l nodes=1:ppn=1:x86
#PBS -l walltime=01:00:00
#PBS -l mem=1gb
#PBS -o testrun.out
#PBS -j oe

matlab <~/CellAnimation/segmentation/segment/AccreSegment.m
perl Classify.pl '~/CellAnimation/segmentation/segment' 'testrun.csv'
matlab <~/CellAnimation/segmentation/segment/AccreResegment.m
perl Classify.pl '~/CellAnimation/segmentation/segment' 'testrun.csv'
matlab <~/CellAnimation/segmentation/segment/AccreFinish.m
